spring:
  application:
    name: document-intelligence-poc

server:
  port: 8080

azure:
  document-intelligence:
    endpoint: ${AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT}
    key: ${AZURE_DOCUMENT_INTELLIGENCE_KEY}
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT}
    key: ${AZURE_OPENAI_KEY}
    deployment-id: ${AZURE_OPENAI_DEPLOYMENT_ID}
    context: ${AZURE_OPENAI_PROMPT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
