spring:
  application:
    name: document-intelligence-poc

server:
  port: 8080

azure:
  document-intelligence:
    endpoint: ${AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT}
    key: ${AZURE_DOCUMENT_INTELLIGENCE_KEY}
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT}
    key: ${AZURE_OPENAI_KEY}
    deployment-id: ${AZURE_OPENAI_DEPLOYMENT_ID}
    context: ${AZURE_OPENAI_CONTEXT}
#     Você é um assistente de IA responsável por extrair informações em documentos.
    prompt: ${AZURE_OPENAI_PROMPT}
#      Avalie o seguinte conteúdo e extraia as seguintes informações específicas em formato JSON,
#      garantindo que os nomes dos campos sejam interpretados como caminhos para a criação de objetos aninhados:
#
#      %s
#
#      Conteúdo a ser avaliado:
#
#      %s
#
#      Observações importantes:
#      * Os nomes dos campos no JSON de retorno devem ser interpretados como caminhos para a criação de objetos aninhados.
#      * Se alguma das informações solicitadas não for encontrada no texto JSON, o campo correspondente no JSON de retorno deve conter o valor "null".
#      * O texto JSON de entrada pode conter outras informações além das solicitadas. Ignore essas informações adicionais.}
#      * A resposta deve conter somente o json com as informações solicitadas. Sem nenhum comentário adicional. Deve iniciar com "{" e terminar com "}"
#      * O conteúdo pode mencionar antigos proprietários responsáveis pela venda dos proprietários atuais, ignore-os e retorne somente os proprietários atuais.

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
